feat: add check for availability of cluster port before `project up`
unikubehq/cli pull request #242
Opened 2021-11-30 21:37 UTC by SteinRobert

Fixes #241 

Adds a simple check for the availability of the cluster port retrieved via GraphQL.

2021-12-01 09:24 UTC, schwobaseggl requested changes
One minor simplification

2021-12-01 09:24 UTC, schwobaseggl commented on src/cli/helper.py
> +    return list(filter(lambda port: port_in_use(port), port_list))
```python
return list(filter(port_in_use, port_list))
```

2021-12-01 12:29 UTC, SteinRobert commented on src/cli/helper.py
> +    return list(filter(lambda port: port_in_use(port), port_list))
Hahaha, fair enough. I'll tackle it.

2021-12-01 21:45 UTC, SteinRobert commented on src/cli/helper.py
> +    return list(filter(lambda port: port_in_use(port), port_list))
Done.

2021-12-06 11:50 UTC, schwobaseggl approved these changes

2021-12-06 11:51 UTC, merged